import { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { AlertTriangle, Bot, CheckCircle, CreditCard, Loader, Lock, User, XCircle } from 'lucide-react';
import { api } from '../lib/api';

export function Account() {
  const [profile, setProfile] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [subscribing, setSubscribing] = useState(false);
  const [cancelling, setCancelling] = useState(false);
  const [banner, setBanner] = useState<'success' | 'cancel' | null>(null);
  const navigate = useNavigate();
  const [searchParams, setSearchParams] = useSearchParams();

  async function fetchProfile() {
    const data = await api.getProfile();
    setProfile(data);
    return data;
  }

  useEffect(() => {
    const checkout = searchParams.get('checkout');
    setSearchParams({}, { replace: true });

    api.getProfile()
      .then((data) => {
        setProfile(data);
        if (checkout === 'success' || checkout === 'cancel') {
          setBanner(checkout);
        }
      })
      .catch(() => navigate('/login'))
      .finally(() => setLoading(false));
  }, [navigate]);

  async function handleSubscribe() {
    setSubscribing(true);
    try {
      const { url } = await api.createCheckoutSession();
      window.location.href = url;
    } catch (err: any) {
      alert(err.message || 'Failed to start checkout. Please try again.');
      setSubscribing(false);
    }
  }

  async function handleCancel() {
    if (!confirm('Cancel your AI Coach Pro subscription? You will keep access until the end of the current billing period.')) return;
    setCancelling(true);
    try {
      await api.cancelSubscription();
      await fetchProfile();
    } catch (err: any) {
      alert(err.message || 'Failed to cancel subscription. Please try again.');
    } finally {
      setCancelling(false);
    }
  }

  if (loading) {
    return <div className="container mt-8" style={{ textAlign: 'center' }}>Loading profile...</div>;
  }

  if (!profile) return null;

  const sub: string = profile.subscription ?? 'free';
  const isPro        = sub === 'pro';
  const isCancelling = sub === 'cancelling';
  const isFree       = sub === 'free';

  return (
    <div className="container animate-fade-in" style={{ padding: '4rem 0' }}>
      <h1 className="mb-8" style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
        <User size={36} /> Profile Overview
      </h1>

      {banner === 'success' && (
        <div style={bannerStyle('success')}>
          <CheckCircle size={20} /> Subscription activated! Welcome to AI Coach Pro.
        </div>
      )}
      {banner === 'cancel' && (
        <div style={bannerStyle('cancel')}>
          <XCircle size={20} /> Checkout cancelled. You were not charged.
        </div>
      )}

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '2rem' }}>

        {/* Stats Panel */}
        <div className="glass-panel" style={{ padding: '2rem' }}>
          <h2 style={{ fontSize: '1.5rem', marginBottom: '1.5rem', color: 'var(--primary-light)' }}>
            Player Stats
          </h2>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            <Row label="Username" value={profile.username} />
            <Row label="ELO Rank" value={<span className="text-gold" style={{ fontWeight: 'bold', fontSize: '1.125rem' }}>{profile.rank}</span>} />
            <Row label="Wins"   value={<span style={{ color: 'var(--primary-light)', fontWeight: 'bold' }}>{profile.wins}</span>} />
            <Row label="Losses" value={<span style={{ color: 'var(--danger)', fontWeight: 'bold' }}>{profile.losses}</span>} />
            <Row label="Ties"   value={<span style={{ fontWeight: 'bold' }}>{profile.ties}</span>} last />
          </div>
        </div>

        {/* AI Coach Billing */}
        <div className="glass-panel" style={{ padding: '2rem', display: 'flex', flexDirection: 'column' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '1.5rem' }}>
            <h2 style={{ fontSize: '1.5rem', display: 'flex', alignItems: 'center', gap: '0.75rem', color: 'var(--accent-gold)' }}>
              <Bot size={28} /> AI Coach Pro
            </h2>
            {isPro && <StatusBadge color="var(--primary-light)" bg="rgba(82,196,98,0.2)">ACTIVE</StatusBadge>}
            {isCancelling && <StatusBadge color="#f59e0b" bg="rgba(245,158,11,0.15)">CANCELLING</StatusBadge>}
          </div>

          <p style={{ color: 'var(--text-muted)', marginBottom: '2rem', lineHeight: 1.6 }}>
            Unlock personalized insights, real-time tactical analysis, and custom opening repertoires generated by our state-of-the-art AI.
          </p>

          <div style={{ background: 'rgba(0,0,0,0.3)', padding: '1.5rem', borderRadius: '12px', border: '1px solid var(--surface-border)', marginBottom: 'auto' }}>
            <h3 style={{ fontSize: '1.25rem', marginBottom: '0.5rem' }}>
              $4.99 <span style={{ fontSize: '0.875rem', color: 'var(--text-muted)', fontWeight: 'normal' }}>/ month</span>
            </h3>
            <ul style={{ listStyle: 'none', color: 'var(--text-muted)', fontSize: '0.875rem', display: 'flex', flexDirection: 'column', gap: '0.5rem', marginTop: '1rem' }}>
              <li>✓ Post-game move analysis</li>
              <li>✓ Tactical missed-opportunity alerts</li>
              <li>✓ Opening coach</li>
            </ul>
          </div>

          <div style={{ marginTop: '2rem', display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
            {isFree && (
              <button className="btn btn-gold w-full" onClick={handleSubscribe} disabled={subscribing} style={{ opacity: subscribing ? 0.7 : 1 }}>
                {subscribing
                  ? <><Loader size={16} style={{ animation: 'spin 1s linear infinite' }} /> Redirecting…</>
                  : <><Lock size={16} /> Subscribe via Stripe</>}
              </button>
            )}

            {isPro && (
              <>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', padding: '0.75rem', borderRadius: '10px', background: 'rgba(82,196,98,0.1)', border: '1px solid var(--primary-light)', color: 'var(--primary-light)', fontWeight: 600 }}>
                  <CheckCircle size={16} /> Active subscription
                </div>
                <button
                  className="btn w-full"
                  onClick={handleCancel}
                  disabled={cancelling}
                  style={{ background: 'transparent', border: '1px solid var(--danger)', color: 'var(--danger)', opacity: cancelling ? 0.7 : 1 }}
                >
                  {cancelling
                    ? <><Loader size={16} style={{ animation: 'spin 1s linear infinite' }} /> Cancelling…</>
                    : 'Cancel Subscription'}
                </button>
              </>
            )}

            {isCancelling && (
              <div style={{ display: 'flex', alignItems: 'flex-start', gap: '0.75rem', padding: '1rem', borderRadius: '10px', background: 'rgba(245,158,11,0.1)', border: '1px solid #f59e0b', color: '#f59e0b', fontSize: '0.875rem' }}>
                <AlertTriangle size={16} style={{ flexShrink: 0, marginTop: 2 }} />
                Your subscription is cancelled and will remain active until the end of the current billing period.
              </div>
            )}
          </div>

          <p style={{ textAlign: 'center', color: 'var(--text-muted)', fontSize: '0.75rem', marginTop: '1rem', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem' }}>
            <CreditCard size={14} /> Secure billing powered by Stripe
          </p>
        </div>

      </div>
    </div>
  );
}

function Row({ label, value, last = false }: { label: string; value: React.ReactNode; last?: boolean }) {
  return (
    <div style={{ display: 'flex', justifyContent: 'space-between', paddingBottom: last ? 0 : '1rem', borderBottom: last ? 'none' : '1px solid var(--surface-border)' }}>
      <span style={{ color: 'var(--text-muted)' }}>{label}</span>
      <span>{value}</span>
    </div>
  );
}

function StatusBadge({ children, color, bg }: { children: React.ReactNode; color: string; bg: string }) {
  return (
    <span style={{ background: bg, color, padding: '0.25rem 0.75rem', borderRadius: '999px', fontSize: '0.75rem', fontWeight: 'bold' }}>
      {children}
    </span>
  );
}

function bannerStyle(type: 'success' | 'cancel'): React.CSSProperties {
  const isSuccess = type === 'success';
  return {
    display: 'flex', alignItems: 'center', gap: '0.75rem',
    padding: '1rem 1.5rem', borderRadius: '12px', marginBottom: '2rem',
    background: isSuccess ? 'rgba(82, 196, 98, 0.15)' : 'rgba(220, 60, 60, 0.15)',
    border: `1px solid ${isSuccess ? 'var(--primary-light)' : 'var(--danger)'}`,
    color: isSuccess ? 'var(--primary-light)' : 'var(--danger)',
  };
}
